### ISSUE TITLE
How to use codeassistant with language servers that have customisations?

### ISSUE THREAD

**Issue by vanarok** [DJAndries/llmvm#4]
An example is in the README:
```
[language-server.llmvm-codeassist-rust]
command = "llmvm-codeassist"
args = ["rust-analyzer"]

[[language]]
name = "rust"
language-servers = [ "llmvm-codeassist-rust" ]
```
But i have the lsp server configuration:
```
[language-server.volar]
args = ["--stdio"]
command = "vue-language-server"

[language-server.volar.config.typescript]
tsdk = "/data/data/com.termux/files/home/.local/share/pnpm/global/5/node_modules/typescript/lib"

[language-server.volar.config.languageFeatures]
semanticTokens = true
references = true
definition = true
typeDefinition = true
callHierarchy = true
hover = true
rename = true
renameFileRefactoring = true
signatureHelp = true
codeAction = true
completion = { defaultTagNameCase = 'both', defaultAttrNameCase = 'kebabCase' }
schemaRequestService = true
documentHighlight = true
documentLink = true
codeLens = true
diagnostics = true
takeOverMode = true

```
I have no idea how to adapt it to codeassist.

**Comment by DJAndries** [comment]
Perhaps this modification to `language-server.volar` would work:

```
[language-server.volar]
command = "llmvm-codeassist"
args = ["vue-language-server", "--stdio"]
```

I have not tested codeassist with anything other than clangd and rust-analyzer, so no guarantees that this will work.

**Comment by vanarok** [comment]
> Perhaps this modification to `language-server.volar` would work:
> 
> ```
> [language-server.volar]
> command = "llmvm-codeassist"
> args = ["vue-language-server", "--stdio"]
> ```
> 
> I have not tested codeassist with anything other than clangd and rust-analyzer, so no guarantees that this will work.

это мне понятно, мне не понятно как передать конфигурацию "[language-server.volar.config]" в таком случае, это критично дял этого lsp, иначе он не запустится

**Comment by vanarok** [comment]
> Perhaps this modification to `language-server.volar` would work:
> 
> ```
> [language-server.volar]
> command = "llmvm-codeassist"
> args = ["vue-language-server", "--stdio"]
> ```
> 
> I have not tested codeassist with anything other than clangd and rust-analyzer, so no guarantees that this will work.

it works just fine.
