### ISSUE TITLE
Custom endpoint for `outsource/openai` backend doesn't seem to work

### ISSUE THREAD

**Issue by joouha** [DJAndries/llmvm#5]
I'm trying to use a custom endpoint for an OpenAI compatible model API.

Running the following gives an error:
```bash
$ lmvm-core generate --model 'outsource/openai-chat/mixtral-8x7b/endpoint=https://mixtral-8x7b.lepton.run/api/v1' --prompt 'Tell me a joke' --max-tokens 64

failed to generate: failed to parse model name
```

Escaping the endpoint URL works, but requests are still sent to the default OpenAI endpoint:

```bash
$ llmvm-core generate --model 'outsource/openai-chat/mixtral-8x7b/endpoint=https:\/\/mixtral-8x7b.lepton.run\/api\/v1' --prompt 'Tell me a joke' --max-tokens 64

failed to generate: backend error: bad http status code: 401 Unauthorized body: {
    "error": {
        "message": "Incorrect API key provided: XXXXXX********************XXX. You can find your API key at https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": "invalid_api_key"
    }
}
```

How do I use a custom endpoint?

**Comment by DJAndries** [comment]
Hey @joouha , I just published new versions of the crates to support custom endpoints within the model ID. In your case, and assuming that your server produces an OpenAI compatible API, you could use `outsource/openai-chat/mixtral-8x7b/endpoint=https://mixtral-8x7b.lepton.run`.

Alternatively, you may specify an `openai_endpoint` value in your outsource configuration. Details are [here](https://github.com/DJAndries/llmvm/tree/master/backends/outsource#configuration).  If you'd like to use this option instead, all of your requests will be sent to your custom endpoint, and you will not be required to specify the custom endpoint in the model ID. You should be able to set `openai_endpoint = "https://mixtral-8x7b.lepton.run" in your `outsource.toml`. Your model ID would simply be `outsource/openai-chat/mixtral-8x7b` in this case.

You will need to update all llmvm package versions via `cargo install` (probably just llmvm-codeassist, llmvm-core and llmvm-outsource).
